name: Manual workflow

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
        - aarch64-linux-musl
        - x86_64-linux-musl
        - i686-linux-musl
        - arm-linux-musleabi
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo 'TARGET = ${{ matrix.target }}' >> config.mak
        make
    - run: |
        make install
    - run: |
        find ./output
    - run: |
        for file in ./output/bin/*; do
          realpath $file
          readelf -a $file
          echo
        done
    - run: |
        tar -czf ./${{ matrix.target }}.tar.gz ./output
        ls -la
    - uses: actions/upload-artifact@v2
      with:
        name: Toolchain - ${{ matrix.target }}
        path: ./${{ matrix.target }}.tar.gz
